### ISSUE TITLE
train TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by lansedebing** [RasaHQ/rasa-demo#265]
PS F:\rasa-demo-master> **python -m rasa_core.train -d domain.yml -s data/core -c policy.yml --debug -o models/dialogue**
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\train.py", line 358, in <module>
    additional_args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\train.py", line 273, in do_default_training
    kwargs=additional_arguments)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\train.py", line 179, in train_dialogue_model
    policies = config.load(policy_config)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\config.py", line 28, in load
    return PolicyEnsemble.from_dict(config_data)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\policies\ensemble.py", line 224, in from_dict
    policy_object = constr_func(**policy)
TypeError: 'NoneType' object is not callable

**Comment by akelad** [comment]
moved this to the rasa-demo repo, because it's more appropriate here. 
Which version of Rasa Core are you using?
Also what are the contents of the `policy.yml`?

**Comment by Akshit99** [comment]
Similar thing is happening to me! This  is my policy content;

```
policies:
  - name: "KerasPolicy"
    epochs: 50
    max_history: 5
  - name: "MemoizationPolicy"
    max_history: 5
  - name: "TwoStageFallbackPolicy"
    nlu_threshold: 0.8
    core_threshold: 0.3
  - name: "FormPolicy"
```
Do I have to add something in domain file as well?
