### ISSUE TITLE
Two Stage Fallback unexpected behaviour

### ISSUE THREAD

**Issue by hossa95** [RasaHQ/rasa-demo#312]
I am trying to use the two stage fallback policy as mentioned in the rasa-demo but it doesn't behave as expected, I tried it in both my project and on the restaurant bot given in the core examples.

I used interactive learning to see the action sequence and here is what I found after an input with low nlu confidence,
```
- action_default_ask_affirmation 
- action_listen 
- user input: yes 
- classified as affirm 
- action_revert_fallback_events 
- action_default_fallback
```
which is not the flow mentioned in docs as it should continue after yes as it was originally well classified, same happens with "deny" it runs the `action_default_fallback` from the first time instead of running `action_default_ask_rephrase` here is my policy: -

```
policies:
  - name: KerasPolicy
    epochs: 50
    max_history: 6
  - name: AugmentedMemoizationPolicy
    max_history: 6
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.8
    core_threshold: 0.3
  - name: FormPolicy
```
the steps I did to apply the two stage fallback is just adding this policy file and adding the `out_of_scope` intent to the `domain.yml` so what is missing here? 

I am using core 0.13.2, also I am not overriding any actions from the default action classes for fallback
