### ISSUE TITLE
Investigate improvements to NLU performance

### ISSUE THREAD

**Issue by akelad** [RasaHQ/rasa-demo#460]
Since Rasa 1.7.0 is released, we should upgrade to it (but not upload the model to Rasa X yet). 
We should also experiment with how much we can improve NLU performance, because some performance issues were fixed with 1.7.0

Specifically try taking out the loss_type here and see how the histograms look like:
- name: EmbeddingIntentClassifier
  epochs: 50
  loss_type: margin

Also good to try out how ConveRT does etc

**Comment by erohmensing** [comment]
Update is being made here https://github.com/RasaHQ/rasa-demo/issues/460

But experimenting with NLU performance after being back on softmax and also checking out convert is definitely still worthwhile!

**Comment by melindaloubser1** [comment]
comparison of current pipeline & convert pipelines the shows convert has best performance. Ignore "config_noloss" -should be "config_marginloss".
 
[nlu_model_comparison_graph.pdf](https://github.com/RasaHQ/rasa-demo/files/4182376/nlu_model_comparison_graph.pdf)

**Comment by akelad** [comment]
@melindaloubser1 can you also post the histograms of each of these? I'm curious to see what kind of confidences we have between wrong and correct classifications

**Comment by melindaloubser1** [comment]
These are all from 5-fold cv since the comparison doesn't output histograms (or at least it didn't the way I ran it?)


## config
![hist](https://user-images.githubusercontent.com/32034278/74252663-f7e81980-4cbb-11ea-8b58-a5bf6c3ad4cf.png)

## config_marginloss
![hist](https://user-images.githubusercontent.com/32034278/74252632-f1f23880-4cbb-11ea-925a-a961c36ca3db.png)

## config_convert

![hist](https://user-images.githubusercontent.com/32034278/74252591-e43cb300-4cbb-11ea-848e-edab5218e4cf.png)

**Comment by erohmensing** [comment]
Nice. Maybe we should also investigate specifically the intent prediction errors that have such high confidence?

**Comment by akelad** [comment]
yes we should! and also can you post the configs you used for each?

**Comment by melindaloubser1** [comment]
Configs:
config.yml
```yml
language: en
pipeline:
- name: WhitespaceTokenizer
- name: CRFEntityExtractor
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: EmbeddingIntentClassifier
  epochs: 50
  ranking_length: 5
```

config_marginloss
```yml
language: en
pipeline:
- name: WhitespaceTokenizer
- name: CRFEntityExtractor
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: EmbeddingIntentClassifier
  epochs: 50
  ranking_length: 5
  loss_type: margin
- name: DucklingHTTPExtractor
  url: http://localhost:8000
  dimensions:
  - email
  - number
  - amount-of-money
- name: EntitySynonymMapper
- name: ResponseSelector
  retrieval_intent: out_of_scope
```

config_convert
```
language: en
pipeline:
- name: ConveRTTokenizer
- name: CRFEntityExtractor
- name: ConveRTFeaturizer
- name: EmbeddingIntentClassifier
  epochs: 50
  ranking_length: 5

```
