### ISSUE TITLE
faq, enter_data and how_to_get_started intents mis-used

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa-demo#623]
The three intents are often used to cover user utterances that merely choose a topic/product. Example training story fragment:
```yml
  - action: utter_ask_explain_nlucorex
  - intent: faq
    entities:
    - product: rasa
  - slot_was_set:
    - product: rasa
  - action: utter_explain_nlu
```
Note that none of these three intents are originally meant for this use case, it is only the lack of a proper intent (or entity) that makes use use these intents for utterances like:
```
help me with rasa open source
rasa x
rasa
whar are the components of rasa?
i want to learn more about rasa
```
This happens especially after `utter_ask_explain_nlucorex` and after `utter_possibilities`.

Ideally, we should add a separate intent that will capture these peculiar utterances and, even more importantly, add an entity where needed, which would capture the topic selected by the user (see [this slide](https://docs.google.com/presentation/d/1drNge3rmXYBPDc9Y5Eo2wUMZ4wF1JTFKrtx44BTui34/edit#slide=id.ga3ef5e8257_0_89) for more context & details).
